services:
  app:
    image: node:lts-alpine
    working_dir: /app
    ports:
      - "3000:3000" # Client
      - "5000:5000" # Server
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run migrate && npm run dev"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
