name: Playwright Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      pull-requests: write
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CI: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm ci

      - name: Start Docker Compose Services
        run: docker compose up -d

      - name: Wait for services to be ready
        run: |
          while ! curl --silent --output /dev/null --fail --max-time 300 http://localhost:3000; do
            sleep 1
          done
          echo "Server is ready!"

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright Tests
        run: |
          npx playwright test --reporter=json > results.json
        continue-on-error: true

      - name: Analyse and Fix Failing Tests
        run: |
          export TRACE_DIR="./test-results"
          export VIDEO_DIR="./test-results/videos"
          node fixTests.js
